### ISSUE TITLE
Federalist-uswds-gatsby feature parity with federalist-uswds-jekyll

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist-uswds-gatsby#20]
#### User Story

A Federalist user using the the federalist-uswds-gatsby template should have nearly the same user experience as a federalist-uswds-jekyll template user from instructions, information and features

#### Background (Optional)

Eddie: 
federalist-uswds-jekyll is our most popular theme, but there is continued interest in using gatby for federalist sites.

Our instance of  18F/federalist-uswds-gatsby has fallen behinid development, but we should ensure it keeps parity with federalist-uswds-jekyll

#### Acceptance Criteria

- [ ] make sure packages are up to date
- [ ] make sure the documentation is up to date
- [ ] make sure the template preview links in the template repository is working
- [ ] make sure all features that work on the federalist-uswds-jekyll template work on the federalist-uswds-gatsby template
- [ ] Change made live via deploy of federalist-uswds-gatsby

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by melpers** [comment]
Any chance the Markdown support will be available when the the Netlify CMS support is added?

**Comment by davemcorwin** [comment]
Hi @melpers ! 

The support for Netlify CMS and updates to the templates (of which this is one) are not related. We will be adding handling of markdown files to this template soon, but keep in mind these are just meant to be starters and you can do whatever you want with them!

The [Gatsby Docs](https://www.gatsbyjs.org/docs/) are incredibly comprehensive and I think [2017-07-19-creating-a-blog-with-gatsby](https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/) blog post includes how to add markdown handling to your Gatsby site.

I'm happy to help with this if you have questions!

**Comment by melpers** [comment]
Thanks for the reply @davemcorwin. I think perhaps I made a bad assumption about why Markdown wasn't supported, and maybe this should be in it's own issue or I have an environment issue.

In order to use gatsby-transformer-remark the core Gatsby needs to be on version 2.12.0 or higher. When I update the federalist starter to that version or higher I get en error: 

```
> gatsby develop

The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! federalist-gatsby-uswds-template@0.1.0 develop: 'gatsby develop'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the federalist-gatsby-uswds-template@0.1.0 develop script.
```

Let me know if this is something to address elsewhere or if you'd like me to send you the .log file. 

EDIT: 
I checked the latest version of the starter, and it's already over 2.12 so I guess there is something in the old starter I was building off of that's causing an issue. I'll start from the latest and see if I can port my changes over.

**Comment by davemcorwin** [comment]
Came to the same conclusion, I'm looking into it as well.

**Comment by amirbey** [comment]
closed by https://github.com/18F/federalist-uswds-gatsby2/issues/5
