### ISSUE TITLE
Gatsby License vs federalist template license

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/federalist-uswds-gatsby#218]
I noticed that the Gatsby license is MIT but this license is CC ... 
- should there be something that references the original Gatsby license? 
- since this project is leveraging the work of Gatsby, should it take the more restrictive license?

**Comment by davemcorwin** [comment]
Thanks @its-a-lisa-at-work !

I am no lawyer or expert in licensing, but my understanding is that as long as the MIT license is included in the source (which it will be since it's downloaded via npm), then we are compliant with the license. The remaining pieces of the software in this template, as well as others, use the CC license as we do with all of our FOSS (including all of the Federalist software), and which is consistent with typical OSS licensing within TTS (https://18f.gsa.gov/open-source-policy/). Users of the template are free to choose their own license since once they clone it, it becomes theirs.

is there something here that I am missing that we should look at addressing?

**Comment by its-a-lisa-at-work** [comment]
Sorry, just getting back to this since 1) I have extra time to actually read and 2) recently had a discussion with someone regarding open source software at TTS so I read the Open Source guide with new eyes. 

I think I am honing in on this portion of the Open Source policy

> This changes when our code repositories include code that was not created by 18F and carries an open license. Code previously released under an open source license and then modified by 18F or its contractors is considered a “joint work” and must be released _under terms permitted by the original open source license_.

So it is probably my lack of understanding, since when I read that, I would assume that since the Gatsby was under MIT that this would be too; but I think I'll have to look closer into what the actual _terms_ of the MIT license are and you're probably right that as long as it is embedded somewhere that its fine, so I'll look for that part of the license that mentions that.

**Comment by its-a-lisa-at-work** [comment]
Ok, I am straight on this now, thank you very much for letting me 'figure it out (loud)' with ya'll. I realize now that if the license were supposed to remain the same, it would have the condition `Same license` on top of the condition `License and copyright notice` and your methodology of including the MIT license in the source is how it gets distributed. 

I didn't realize how easy and simple the MIT license is!
